### ISSUE TITLE
Failed to prepare track: request not ready.

### ISSUE THREAD

**Issue by smlz** [radiorabe/klangbecken#110]
A playlist can get blocked. In the logs we find the following entry:
```
Aug 25 12:37:23 vm-0016.audio.int.rabe.ch liquidsoap[31847]: 2021/08/25 12:37:23 [music:1] Failed to prepare track: request not ready.
```
Apparently this happens, when a track gets deleted but liquidsoap fails to reload the playlist. See https://github.com/AzuraCast/AzuraCast/issues/1415 and https://github.com/savonet/liquidsoap/issues/735.

Changing the order of what happens first (deleting the file vs. updating the playlist file) in https://github.com/radiorabe/klangbecken/blob/master/klangbecken/playlist.py#L392-L399 might solve the problem.

**Comment by smlz** [comment]
I tested this case again and can confirm that this happens, when a track that has been accepted for playback by a decoder gets deleted before playback starts. This is a bug in the version of Liquidsoap we use. Liquidsoap should keep an open file descriptor to the file as of the moment a file has been accepted for playback. Or at the very least not get stuck after this happens and continue with the next track.

I can reproduce this bug on Liquidsoap version 1.3.7. The problem is solved in the current stable version 1.4.4.

As this bug is fixed in newer versions of liqudsoap, the problem occurred only once in almost two years, and we know what to do when it happens, I suggest that we do not invest too much brain power on this issue ... :thinking:

**Comment by smlz** [comment]
Liquidsoap apparently does not like when files get deleted. Just found this in the logs from this morning: 
```
Sep 14 13:03:56 vm-0016.audio.int.rabe.ch liquidsoap[2276]: 2021/09/14 13:03:56 [music:1] Finished with a non-existent file?! Something may have been moved or destroyed during decoding. It is VERY dangerous, avoid it!
```

**Comment by spameier** [comment]
Should not happen again because we are reloading the playlists from the frontend now.
