### ISSUE TITLE
Enable testing for Python 3.11, deprecate Python 3.7

### ISSUE THREAD

**Issue by smlz** [radiorabe/klangbecken#159]

**Comment by hairmare** [comment]
it looks like 3.11 is surfacing some warnings/errors:

> klangbecken/klangbecken/player.py:4: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13

I think we can ignore this for now given that we'll probably be running on py3.9 for the foreseeable future

> klangbecken/klangbecken/.tox/py311/lib/python3.11/site-packages/werkzeug/routing.py:1073: ResourceWarning: Unclosed file <tempfile.SpooledTemporaryFile object at 0x7f45ca894ee0>
  code = compile(module, "<werkzeug routing>", "exec")
ResourceWarning: Enable tracemalloc to get the object allocation traceback

Not sure wh'at going on here, most likely something we'll have to revist after merging #150 if that doesn't fix it
