### ISSUE TITLE
Ensure, that songs are not played more than once a day

### ISSUE THREAD

**Issue by smlz** [radiorabe/klangbecken#21]

**Comment by smlz** [comment]
Currently there is no control over what gets played when. Because with every change the playlist gets reloaded, the same song might get played in short succession. We should ensure a minimum delay that is dependent on the playlist.
* Once a day for classics
* Once in three days for the standard playlist (music)
* Once an hour for jingles

**Comment by spameier** [comment]
closed #21 via #45
