### ISSUE TITLE
Next song starts after delay when coming on air (~30s)

### ISSUE THREAD

**Issue by spameier** [radiorabe/klangbecken#27]
When Klangbecken comes on_air ('1' received by `saemubox_listener.py`) the next song only starts after a timeout of around 30 seconds.

This is due to not setting `bufferize` to `false` in `klangbecken.liq`

https://github.com/radiorabe/klangbecken/blob/c19c80d3c3cf86cc2328d90ae47947751872c385/klangbecken.liq#L206

See [alsa.output](https://www.liquidsoap.info/doc-1.3.7/reference.html#output.alsa) in Liquidsoap documentation.

**Comment by hairmare** [comment]
Reclosing since we are tracking this in #44
