### ISSUE TITLE
Titel können nicht mehr manuell (play next) ausgelöst werden

### ISSUE THREAD

**Issue by hairmare** [radiorabe/klangbecken#29]

**Comment by hairmare** [comment]
Es könnte sein das das schon gefixt wurde.

**Comment by spameier** [comment]
Passiert nach langer Laufdauer und kann mit Reboot gelöst werden. Deshalb tiefere Prio.

**Comment by hairmare** [comment]
Zusätzlich wollte das liquidsoap Skript `/var/lib/klangbecken/prio.m3u` löschen was aufgrund von Rechten nicht mehr funktioniert hat. Ob da die Rechte zu fixen was hilft punkto diesem Issue ist mir aber unklar.

**Comment by smlz** [comment]
Das sollte jetzt gefixt und deployed sein. Falls es wieder auftreten sollte, wär's dann ein neuer Bug.
