### ISSUE TITLE
Songs die schon mal funktioniert haben, gehen dann auf einmal nicht mehr anscheinend (oder zählen, werden aber nicht gespielt..)

### ISSUE THREAD

**Issue by hairmare** [radiorabe/klangbecken#35]

**Comment by spameier** [comment]
zum Beispiel **Tearz** von **El Michels Affair**

**Comment by smlz** [comment]
This bug cannot be reproduced.

The mentioned song has been played this morning,
![Screenshot from 2020-08-29 19-37-30](https://user-images.githubusercontent.com/60396/91642876-28f92300-ea2f-11ea-96e5-caab4f5b2379.png)

has been logged by the Klangbecken, 
![Screenshot from 2020-08-29 19-39-22](https://user-images.githubusercontent.com/60396/91643002-f00d7e00-ea2f-11ea-8b48-7aa3c6edd5d7.png)

and has been recorded in the archives and been recognized by ARCCloud.
![Screenshot from 2020-08-29 19-40-32](https://user-images.githubusercontent.com/60396/91643018-0582a800-ea30-11ea-81ef-07ab9b35152f.png)
