### ISSUE TITLE
Priorität-Einstellung für Classics wäre auch toll. 

### ISSUE THREAD

**Issue by hairmare** [radiorabe/klangbecken#41]
Also wenn man definieren kann, ob wie jetzt ca. jeder fünfte oder beispielsweise jeder dritte oder zehnte Song aus den Classics kommen soll

**Comment by spameier** [comment]
low prio

**Comment by smlz** [comment]
Creating an UI and and API for this is possible, but will take time.

But changing the setting is a simple one-liner, and deploying it should not take more than five minutes.

**Comment by hairmare** [comment]
most likely this story needs further clarification... how often would this setting be tweaked? does it need to be coverned by a scheduling component (ie. play more classics in the night vs. daytime)?

if this is about tuning the current value with the aims of finding the right value then i would probably opt at changing it via simple change, if more is needed then we should think about and api and the needed ui.

**Comment by spameier** [comment]
Nicht mehr aktuell
